FORMAT: 1A
HOST: https://helloworld-gse00001975.apaas.em2.oraclecloud.com/

# Dropwizard Hello World

The most basic of APIs, Hello World

## Usage [/hello-world{?name}]

### Say Hello [GET]
Says hello to the provided name parameter. 

+ Parameters
    + name: Dillon (string) - person to greet.

+ Response 200 (application/json)

        
        {
        
            "id": 3,
            "content": "Hello, Dillon!"
        
        }
